---
title: "rscloud getting started"
author: "Tareef Kawaf"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The rscloud package is meant to provide the R user with access to the REST based APIs available in rstudio.cloud.  To get started, you will need to retrieve your CLIENT_KEY and CLIENT_SECRET and store them in a config.yml file.  Before running through any of the functions, you need to call the initialize_token function.  This will establish a connection that should be valid for 60 minutes.  You can call the refresh_token function if you need to run additional commands post the 60 minutes.

This package will provide you with the ability to:

* List all of your spaces
* Invite users to a space
* Add/remove users from a space
* Discover the roles in a space
* Retrieve the list of projects in a space

The current release of the package does not support the creation/deletion of spaces at this time.

## config.yml

For this release, your config.yml file needs to look something like this:


```
default:
 CLIENT_ID: "YOUR CLIENT ID"
 CLIENT_SECRET: "YOUR CLIENT SECRET" 
```

## Running rscloud

You should be able to test out that the package is working by running:

```
rscloud::initialize_token()

rscloud::get_spaces()

```

The `initialize_token()` function will create a token that is valid for 60 minutes.  A valid token is required prior to any other calls in this package.  Should the token expire, you can refresh it by calling `refresh_token()`.  


